# Generated by Django 5.0.2 on 2024-02-17 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('db_isolates', models.CharField(max_length=255)),
                ('db_seqdef', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('locus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.locus')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.metadatacategory')),
            ],
        ),
        migrations.AddField(
            model_name='locus',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.organism'),
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('db_id', models.PositiveIntegerField()),
                ('alleles', models.ManyToManyField(to='targets.allele')),
                ('metadata', models.ManyToManyField(to='targets.metadata')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.organism')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genomes', models.ManyToManyField(to='targets.genome')),
                ('loci', models.ManyToManyField(to='targets.locus')),
            ],
        ),
        migrations.CreateModel(
            name='TargetCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('loci', models.ManyToManyField(to='targets.locus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.project')),
            ],
        ),
    ]
