# Generated by Django 5.0.2 on 2024-02-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('db_isolates', models.CharField(max_length=255)),
                ('db_seqdef', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targets.organism')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='MetadataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.project')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.genome')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.metadatacategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.project')),
            ],
        ),
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.project')),
            ],
        ),
        migrations.AddField(
            model_name='genome',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.project'),
        ),
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.genome')),
                ('locus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.locus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.project')),
            ],
        ),
        migrations.CreateModel(
            name='TargetCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('loci', models.ManyToManyField(to='targets.locus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.project')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
