# Generated by Django 5.0.2 on 2024-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allele',
            name='value',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
