# Generated by Django 5.0.2 on 2024-02-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_alter_project_options_alter_targetcollection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targets.organism'),
        ),
    ]
