# Generated by Django 5.0.2 on 2024-02-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_alter_allele_value_alter_project_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genome',
            options={'ordering': ('name',)},
        ),
    ]
