# Generated by Django 5.0.2 on 2024-02-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_alter_project_organism'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='db_id',
        ),
        migrations.AlterField(
            model_name='genome',
            name='name',
            field=models.PositiveIntegerField(),
        ),
    ]
