# Generated by Django 5.0.2 on 2024-02-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_alter_genome_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allele',
            unique_together={('project', 'locus', 'genome')},
        ),
        migrations.AlterUniqueTogether(
            name='genome',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='locus',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('project', 'category', 'genome')},
        ),
        migrations.AlterUniqueTogether(
            name='metadatacategory',
            unique_together={('project', 'name')},
        ),
        migrations.AddIndex(
            model_name='allele',
            index=models.Index(fields=['project', 'locus', 'genome'], name='targets_all_project_953d50_idx'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(fields=['project', 'category', 'genome'], name='targets_met_project_303cd7_idx'),
        ),
    ]
