# Generated by Django 5.0.2 on 2024-02-22 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_alter_allele_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='genome',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='project',
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Allele',
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
    ]
