# Generated by Django 5.0.2 on 2024-02-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_remove_genome_db_id_alter_genome_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatacategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
