# Generated by Django 5.0.2 on 2024-02-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_alter_metadata_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='InputData',
        ),
    ]
