# Generated by Django 5.0.2 on 2024-02-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_locus_alleles'),
    ]

    operations = [
        migrations.AddField(
            model_name='genome',
            name='alleles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='metadata',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
