# Generated by Django 5.0.2 on 2024-02-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0008_genome_alleles_genome_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacategory',
            name='genomes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadatacategory',
            name='values',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
