# Generated by Django 5.0.2 on 2024-02-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0009_metadatacategory_genomes_metadatacategory_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imputed_data',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
