# Generated by Django 5.0.2 on 2024-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0010_project_imputed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcollection',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
