# Generated by Django 5.0.2 on 2024-02-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0011_targetcollection_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targetcollection',
            unique_together={('project', 'name')},
        ),
    ]
