# Generated by Django 5.0.2 on 2024-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0012_alter_targetcollection_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatacategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
