# Generated by Django 5.0.2 on 2024-02-29 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0013_alter_metadatacategory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadatacategory',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='alleles',
            new_name='n_alleles',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='metadata',
            new_name='n_metadata',
        ),
        migrations.RenameField(
            model_name='locus',
            old_name='alleles',
            new_name='n_alleles',
        ),
        migrations.RenameField(
            model_name='metadatacategory',
            old_name='genomes',
            new_name='n_genomes',
        ),
        migrations.RenameField(
            model_name='metadatacategory',
            old_name='values',
            new_name='n_values',
        ),
        migrations.AlterUniqueTogether(
            name='metadatacategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='genome',
            name='selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locus',
            name='selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metadatacategory',
            name='selected',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele', models.CharField(blank=True, max_length=16, null=True)),
                ('imputed', models.CharField(blank=True, max_length=16, null=True)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.genome')),
                ('locus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.locus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.project')),
            ],
            options={
                'unique_together': {('project', 'genome', 'locus')},
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=16, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.metadatacategory')),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.genome')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.project')),
            ],
            options={
                'unique_together': {('project', 'genome', 'category')},
            },
        ),
    ]
