# Generated by Django 5.0.2 on 2024-02-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0014_alter_metadatacategory_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allele',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together=set(),
        ),
    ]
