# Generated by Django 5.0.2 on 2024-02-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0015_alter_allele_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allele',
            unique_together={('project', 'genome', 'locus')},
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('project', 'genome', 'category')},
        ),
    ]
