# Generated by Django 5.0.2 on 2024-03-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primercollection',
            name='project',
        ),
        migrations.AlterField(
            model_name='primercollection',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
