# Generated by Django 5.0.2 on 2024-03-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primers', '0002_remove_primercollection_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primercollection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
